### ISSUE TITLE
Request: Ability to allow icon state color for light/power entity

### ISSUE THREAD

**Issue by Codename-11** [dangreco/threedy#12]
I was curious if it was possible to allow the light entity to display its state in the icon? I realize for the power entity the card already gives you the online/offline status so I imagine that's not particularly necessary.

**Comment by dangreco** [comment]
Of course! Would it be more intuitive to have a different icon for on/off state, or just a change in color? (Or both!)

**Comment by dangreco** [comment]
I just implemented this in the latest commit -- if you want to try this before next release you can clone the repo and manually build it!

**Comment by e1miran** [comment]
This appears to only have been implemented for the light_entity. Can it also be implemented on the power_entity, please?
