### ISSUE TITLE
Temperature Units

### ISSUE THREAD

**Issue by MechEng70** [dangreco/threedy#15]
The units for HA are in F and therefore show up on the card as F.  Is there a toggle that allows to convert and display units in either format?

![2021-02-02_14-47-54](https://user-images.githubusercontent.com/11697710/106672897-b05e3b80-6565-11eb-89f9-3c2e1d65b390.png)

**Comment by dangreco** [comment]
I can implement this! ETA is initial release (Sunday Feb. 6)

**Comment by dangreco** [comment]
Added in [my most recent commit](https://github.com/dangreco/threedy/commit/b16bc2b66707e13c9362a5a4b18c8ed046e194c2). Read the README for usage. Closing this issue -- expect a release Sunday as mentioned earlier.

Thanks!

**Comment by MechEng70** [comment]
Hi @dangreco, what was the timing on the release?  Would like to test it.
