### ISSUE TITLE
Request: Elapsed time / Time remaining formatting

### ISSUE THREAD

**Issue by RoboMagus** [dangreco/threedy#21]
Love the card!
But a minor gripe I have is that the stats don't update every second, and elapsed time has second precision.
On the one hand for short prints a higher precision time could be nice, but also for (very) long prints rounding to minutes or maybe even hours could be preffered.

On a related note, I already snuck it into the title, a time remaining field would also be a nice addition.

**Comment by dangreco** [comment]
Thanks!

Regarding the frequency of the stats updating, this is a bottleneck within the OctoPrint x Home Assistant integration itself. The only way to change this to every second would be on that end, as the card just uses whatever data Home Assistant has. 
For the time however, this could be updated consistently with a relatively simple implementation. I'll work on that. The time remaining field will also be a straightforward addition.

In regards to how the elapsed time is formatted, I am thinking of two possible solutions:

1. Provide the user with an option to specify a formatting string (e.g. `'HH:mm::ss'`)
2. Implement a rounding function that rounds in the manner you specified


Let me know your thoughts!

**Comment by RoboMagus** [comment]
Wow, you're a fast responder!

I thought that the interaction with Octoprint would be too slow indeed to have an update every second. That would almost never be necessary anyway. 
Having the option to specify a formatting string would be ideal I think, as it would allow for the most flexible formatting by the user. I think the rounding would also be taken care of using standard time formatting implementations.
If not, a 30s difference is no biggie.

Keep up the good work!

**Comment by dangreco** [comment]
> Wow, you're a fast responder!

Haha, basically done with my midterm exams so I've got too much free time!

[moment.js](https://momentjs.com/) includes relative time displaying, e.g.:
`moment().endOf('day').fromNow();          // in 10 hours`
I was thinking that a config variable such as `round_time` would choose between using a user-provided formatter/default formatter and the relative time. 

>  If not, a 30s difference is no biggie.

I'm pretty sure I could utilise the `setTimeout()` function in JS to update the time displayed every second, no problem.

I'll work on this a bit later and most likely have a release out tonight with these features!

**Comment by dangreco** [comment]
Implemented in [the latest release](https://github.com/dangreco/threedy/releases/tag/2021.0.3)!!

Thanks so much for your support & ideas!
