### ISSUE TITLE
Decimal points need limitations

### ISSUE THREAD

**Issue by MechEng70** [dangreco/threedy#23]
The temperature has approx 10 significant digits.  Can you limit them to 1 or 2?

![image](https://user-images.githubusercontent.com/11697710/109542463-f087df80-7a79-11eb-9a07-6759648ded66.png)

**Comment by dangreco** [comment]
Oh wow oops, yep!

**Comment by dangreco** [comment]
Included in the [latest release](https://github.com/dangreco/threedy/releases/tag/2021.0.4).

Thanks!
