### ISSUE TITLE
24 hour clock mode

### ISSUE THREAD

**Issue by Jan-Ka** [dangreco/threedy#4]
I would like to request a yml toggle to enable [24 hour](https://en.wikipedia.org/wiki/24-hour_clock) mode.

Thanks :)

**Comment by dangreco** [comment]
I can do that ASAP! Thanks!

**Comment by dangreco** [comment]
Added in latest commit! Publishing a new release later tonight with the commit in it -- the readme details usage.

Thanks again!!
