### ISSUE TITLE
FR: button to toggle lights and printer

### ISSUE THREAD

**Issue by Sennevds** [dangreco/threedy#5]
Hey first of all really nice job on the card! Looks super.
So this is a little feature request that has no rush. It would be cool if you could add a optional switch to toggle a light and a separate optional switch to turn on the printer (I have a smart outlet which controls the printer)

**Comment by dangreco** [comment]
Added in latest commit! I will be uploading another release tonight that will contain the commit. Reference the readme for instructions on uses. Right now the implementation is basic -- I will be eventually adding an animation on button press.

Thanks for the suggestion!
