### ISSUE TITLE
Card-Mod style issue

### ISSUE THREAD

**Issue by Freshhat** [dangreco/threedy#8]
Hi, first of all great work on that card. 

Already integrated it into my overall overview into Lovelace. But I can't figure out how to apply different styles using card-mod to fit perfectly into my theme.

I just wanted to remove the box-shadow:

![image](https://user-images.githubusercontent.com/18122096/106293150-f6598d80-624d-11eb-89f8-e4f40cc4fcf1.png)

```              card:
                type: 'custom:threedy-card'
                style: |
                  ha-card: {
                    box-shadow: none !important;
                  }
                base_entity: sensor.ender_3_pro
                name: Ender 3 Pro
                printer_type: I3
                monitored:
                  - Status
                  - ETA
                  - Elapsed
                  - Hotend
                  - Bed
                theme: Default
                font: Roboto
                scale: 0.5
                use_24hr: true
                round: false
```
If i remove it directly under the element.style {} block in my Browser then it's working...
Any advise on that?

**Comment by dangreco** [comment]
It seems to be an issue with how card-mod functions -- it tries to attach itself to the shadow DOM of the element, but my element doesn't have a shadow DOM to begin with. 
I'm working on wrapping the card in a shadow DOM to fix this.

**Comment by dangreco** [comment]
Upon further research, the ```lovelace-card-mod``` readme says the following:
![screenshot](https://i.imgur.com/W2Oi2y7.png)

I attempted this workaround with my card and it works. For your situation, the style would look like: 

```css
threedy-card > div {
    box-shadow: none !important;
}
```

Hopefully this helps!
